---
- hosts: build_servers
  sudo: no
  roles:
    - elixir_build

# This lookup is required, because looking up the app version
# is done at the build role and needs to transfer over
# to the deploy role.

- hosts: all
  vars:
    app_version: "{{ lookup('file', '~/releases/{{ app_name }}_version') }}"

- hosts: production
  sudo: no
  roles:
    - { role: "elixir_deploy", action: "upgrade" }
