---
- name: "clean old repo"
  file: path="{{ project_path }}" state=absent
- name: "ensure repo projects directory"
  file: path="~/projects" state=directory
- name: "fetch repo"
  git:
    repo: "{{ repo_url }}"
    version: "{{ git_ref }}"
    accept_hostkey: yes
    force: True
    dest: "{{ project_path }}"
    ssh_opts: "-o ForwardAgent=yes"
- name: "install repo dependencies"
  command: bash -lc "mix deps.get" chdir="{{ project_path }}"
  environment:
    MIX_ENV: "{{ mix_env }}"
- name: "build release"
  command: bash -lc 'SERVER=1 mix release' chdir="{{ project_path }}"
  environment:
    MIX_ENV: "{{ mix_env }}"
    PORT: "{{ app_port }}"
- name: "get release version"
  command: bash -lc "mix run -e 'IO.puts Mix.Project.config[:version]'" chdir="{{ project_path }}"
  register: app_version
- name: "fetch release tar"
  fetch: src='{{ project_path }}/rel/{{ app_name }}/releases/"{{ app_version }}"/{{ app_name }}.tar.gz' dest="/tmp"
