---

# This lookup is required, because looking up the app version
# is done at the build role and needs to transfer over
# to the deploy role.

- hosts: all
  vars:
    app_version: "{{ lookup('file', '~/releases/{{ app_name }}_version') }}"

- name: "ensure releases dir"
  file: path="~/releases" state=directory

- name: "ensure apps dir"
  file: path="~/apps" state=directory

- name: "ensure app name dir"
  file: path="~/apps/{{ app_name }}" state=directory

# ------
# ACTION == "START"
# ------

- when: action == "start"
  name: "extract release tar to hosts"
  unarchive:
    src: "~/releases/{{ app_name }}.tar.gz"
    dest: "~/apps/{{ app_name }}/"

- when: action == "start"
  name: "run app"
  command: bash -lc "PORT=3000 ~/apps/{{ app_name }}/bin/{{ app_name }} start"

# ------
# ACTION == "UPGRADE"
# ------

- when: action == "upgrade"
  name: "ensure version dir"
  file:
    path: "~/apps/{{ app_name }}/releases/{{ app_version }}"
    state: "directory"

- when: action == "upgrade"
  name: "copy release tar to its release version folder"
  copy:
    src: "~/releases/{{ app_name }}.tar.gz"
    dest: "~/apps/{{ app_name }}/releases{{ app_version }}/"

- when: action == "upgrade"
  name: "perform hot code upgrade"
  command: bash -lc "PORT=3000 ~/apps/{{ app_name }}/bin/{{ app_name }} upgrade {{ app_version }}"
