---
- name: "ensure releases dir"
  file: path="~/releases" state=directory

- name: "ensure apps dir"
  file: path="~/apps" state=directory

- name: "ensure app name dir"
  file: path="~/apps/{{ app_name }}" state=directory

- name: "extract release tar to hosts"
  unarchive:
    src: "~/releases/{{ app_name }}.tar.gz"
    dest: "~/apps/{{ app_name }}/"

- name: "run app"
  command: bash -lc "PORT=3000 ~/apps/{{ app_name }}/bin/{{ app_name }} start"
